source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@stash.grupa.onet:7999/pod/dlinternalcocoapods.git'

use_frameworks!
inhibit_all_warnings!

def common_pods
    platform :ios, '8.0'
    # List pods here
    pod 'ASNotificationCenter'
    pod 'DLMessageBus'
    pod 'DLDeviceHelper'
    pod 'DLConfigReader'
    pod 'DLCocoaLumberjackHelper'
    pod 'DLAppHelper'
    pod 'DLUIExtensions'
end

def fabric_pods
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'DLRib' do
    common_pods
    fabric_pods
end

target 'DLRibTests' do
    common_pods
    fabric_pods
end

target 'DLRibUI' do
    common_pods
    fabric_pods
    pod 'DLRemoteControl'
end

target 'DLRibUITests' do
    platform :ios, '9.0'
    pod 'DLTestHelpers'
end

