source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@stash.grupa.onet:7999/pod/dlinternalcocoapods.git'

use_frameworks!
inhibit_all_warnings!

def common_pods
    platform :ios, '9.0'
    pod 'DLCocoaLumberjackHelper', '~> 5.0.0'
    pod 'DLAppHelper', '~> 5.0.0'
    pod 'SwiftLint', '~> 0.25.0'
end

def fabric_pods
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'DLPrivacy' do
    common_pods
    fabric_pods
    pod 'DLTestMockHelper/MainApp', '~> 5.0.0'
    pod 'DLTestHelpers/Common', '~> 5.0.0'
end

target 'DLPrivacyTests' do
    common_pods
    fabric_pods
    pod 'DLTestMockHelper/MainApp', '~> 5.0.0'
    pod 'DLTestHelpers/Common', '~> 5.0.0'
end

target 'DLPrivacyUI' do
    common_pods
    fabric_pods
    pod 'DLTestMockHelper/UIApp', '~> 5.0.0'
    pod 'DLTestHelpers/UIApp', '~> 5.0.0'
    
end

target 'DLPrivacyUITests' do
    platform :ios, '9.0'
    pod 'DLTestMockHelper/UITests', '~> 5.0.0'
    pod 'DLTestHelpers/UITests', '~> 5.0.0'
end

